### ISSUE TITLE
MaxMind GeoIP database requires license, breaks sign up on fresh installs

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#88] opened 2020-02-15 15:21 UTC
**Errors**

During installation, the `geoipupdate` command fails with one of the following error messages (depending on its version):
```
Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=3a5d812fa6d536c0e18a6271023f5669&user_id=999999&edition_id=GeoLite2-City
```
```
error retrieving updates: unexpected HTTP status code: 401 Unauthorized: An account ID and license key are required to use this service.
```

The failure causes the registration page (/accounts/sign_up) to crash with the following error:
```
IOError - GeoIP2 - Error opening the specified MaxMind DB file: /usr/share/GeoIP/GeoLite2-City.mmdb:
  app/views/accounts/registrations/new.html.erb:22:in `block in _app_views_accounts_registrations_new_html_erb__...'
  app/views/accounts/registrations/new.html.erb:3:in `_app_views_accounts_registrations_new_html_erb__...'
  lib/rack/response_timer.rb:12:in `_call'
  lib/rack/response_timer.rb:7:in `call'
```

**Cause**

The MaxMind GeoLite2 database requires a (free) license key since 30 December 2019 due to issues related to privacy regulations. See https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ for details.

**Workaround**

The sign up page can be fixed by changing https://github.com/NZOI/nztrain/blob/97d96ac3002ce39ca57a3bd26e3bcf760f7bad78/app/views/accounts/registrations/new.html.erb#L22 to
```ruby
  <%= f.country_select(:country_code, selected: @user.country_code, priority_countries: ["NZ", "AU"]) %></p>
```

**Proposed Solution**

I propose removing the GeoIP database altogether. As far as I can tell, its only purpose is to set the default country on the registration page. To me it's not worth the hassle of obtaining a license key (and maintaining the install script, and downloading the packages).

Since almost all our users are from New Zealand, I suggest we simply set the default to NZ. If we don't want non-NZ users to accidentally leave the country as NZ, we can set the default to a placeholder and force users to explicitly select a country (the cost is that the majority of the users will then need two additional clicks to select NZ).

**Alternative Solution**
[Replace with a different database](https://github.com/NZOI/nztrain/pull/108#issuecomment-618150282)

**Related issues**
#37 - Investigate geocoder dependency

**Comment by puqeko** [comment] 2020-02-15 18:18
Removing GeoID seems reasonable

**Comment by lambda-fairy** [comment] 2020-04-23 00:13
Is #37 a duplicate of this?

(For the record, I support this change.)

**Comment by tom93** [comment] 2020-04-23 02:55
Yes, they are related. I'll add links.

**Closed** 2023-02-18 12:42 UTC
